### ISSUE TITLE
Find common issues with course files

### ISSUE THREAD

**Issue by OmarIthawi** [appsembler/openedx-course-migration-tool#2]
During bulk import of the courses we've encountered the following issues. Some can be done with manageable effort, however, others are blockers which we don't know how to solve:

### Blocker Issues Requiring Microsoft Feedback
 - [ ] Microsoft achievement services depend on the full course id as in `course-v1:Microsoft/ExcelDataScience/Q4`. However, most of the courses has a different organisation ID and run ID set to `course` (like all edX exported courses, run doesn't get exported).

### Issues which Can be Solved Manually
 - [ ] Some course have the default about page, those courses shouldn't be imported as is, most probably those courses are just outdated
  - [ ] Figure out which courses are outdated, and avoid importing them, instead ask for the most up to date ones

### Solvable Issues by Update the course-import Script:

 - [ ] The migration script doesn't support spaces in course file names, replacing spaces (and other special chars should do)
- [ ] Some courses comes with their libraries bundled in a single `.zip` file, ideally importing those courses should be supported automatically

**Comment by natea** [comment]
@OmarIthawi do we know that PartnerQ4 courses should *not* be imported? I think we should send this feedback to the team at Microsoft responsible for the courses to get their feedback and some clarification on all of your checklist items. /cc @abeals

**Comment by OmarIthawi** [comment]
@natea I still haven't checked the courses. AFAIK they _should_ be imported, with the org being modified to `Microsoft`.

Please do ping them and CC me, I could ping the author via GitHub but GitHub notifications are not very reliable.

This is a pain point that is fairly automatable in the course import script, unless we come up with a better course management solution.

**Comment by OmarIthawi** [comment]
FYI @melvinsoft @amirtds @tkeemon @ms-hukoyun

**Comment by natea** [comment]
@OmarIthawi could some of the files that you thought were courses actually be course libraries (hence the reason why they wouldn't have the "Microsoft" org id)?
https://assets.microsoft.com/en-us/laas-course-library-addenda.pdf

**Comment by OmarIthawi** [comment]
@natea there are indeed course libraries, but the non-Microsoft courses are just courses with what it seems to be a misspelled course org. I'm working on this issue right now, should be resolved.

**Comment by tkeemon** [comment]
@OmarIthawi I think we're getting ahead of ourselves. Before we start automating any of these changes, let's make sure they're necessary in the first place. e.g.:

> Some courses has the incorrect org name (PartnerQ4 or something like that) those courses should not be imported

When I did my last MSLP course import, all courses had the `PartnerQ4` organization. Let's check with MS to make sure this is incorrect before unilaterally making this change. If the course ID is incorrect, then there are almost definitely going to be problems connecting it to the MS Achievements Service. 

>  Some courses get imported with course (Microsoft/EXCEL101/course) as the run, it would be better to put the course authoring year instead Microsoft/EXCEL101/2017

Ditto above. 

>  Figure out which courses are outdated, and avoid importing them, instead ask for the most up to date ones

The courses are provided by MS to the customer, then the customer gives them to us. I'd expect any courses that we receive to be the most up to date version.

**Comment by natea** [comment]
>>Figure out which courses are outdated, and avoid importing them, instead ask for the most up to >>date ones

>The courses are provided by MS to the customer, then the customer gives them to us. I'd expect >any courses that we receive to be the most up to date version.

The problem is with the previously imported courses, not the new courses that we're importing. Every time MSFT releases new versions of the courses, we need to figure out a way to deprecate the old versions.

**Comment by OmarIthawi** [comment]
Except for https://github.com/appsembler/msft-courses/issues/2, this repo solves the problems listed above:

 - https://github.com/appsembler/msft-courses/pull/1
